DROP TABLE IF EXISTS weather_data;

CREATE TABLE weather_data (
    id SERIAL PRIMARY KEY,
    city VARCHAR(100),
    region VARCHAR(100),
    country VARCHAR(100),
    lat NUMERIC(10,4),
    lon NUMERIC(10,4),
    tz_id VARCHAR(100),
    local_time TIMESTAMP,
    localtime_epoch BIGINT,
    last_updated TIMESTAMP,
    last_updated_epoch BIGINT,
    temp_c NUMERIC(5,2),
    temp_f NUMERIC(5,2),
    is_day INT,
    condition_text VARCHAR(100),
    condition_icon VARCHAR(255),
    condition_code INT,
    wind_mph NUMERIC(5,2),
    wind_kph NUMERIC(5,2),
    wind_degree INT,
    wind_dir VARCHAR(10),
    pressure_mb NUMERIC(7,2),
    pressure_in NUMERIC(7,2),
    precip_mm NUMERIC(5,2),
    precip_in NUMERIC(5,2),
    humidity INT,
    cloud INT,
    feelslike_c NUMERIC(5,2),
    feelslike_f NUMERIC(5,2),
    windchill_c NUMERIC(5,2),
    windchill_f NUMERIC(5,2),
    heatindex_c NUMERIC(5,2),
    heatindex_f NUMERIC(5,2),
    dewpoint_c NUMERIC(5,2),
    dewpoint_f NUMERIC(5,2),
    vis_km NUMERIC(5,2),
    vis_miles NUMERIC(5,2),
    uv NUMERIC(5,2),
    gust_mph NUMERIC(5,2),
    gust_kph NUMERIC(5,2)
);
